#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	create user docker;
	create database docker with owner docker;
	grant all on database docker to docker;
EOSQL

psql -v ON_ERROR_STOP=1 --username docker --dbname docker <<-EOSQL
	create table executions
	(
		id int generated by default as identity,
		timestamp timestamp with time zone not null,
		commands numeric not null,
		result numeric not null,
		duration numeric not null
	);
EOSQL